name: Update README with Tables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run README generator script
        run: python generate_readme.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update README with stylish dynamic tables"
          branch: update-readme
          title: "Update README with latest file links"
          body: "This PR was created automatically to update the README."
